name: Deploying Application

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      #- run: cp .env.example .env
      - run: npm i
      - run: npm run build --if-present
      - run: cp -r /home/lucas-giraldelli/git-runners/actions-runner/_work/cerv-infancia/cerv-infancia/dist/. /var/www/html
